### ISSUE TITLE
Web form should allow for enrollment

### ISSUE THREAD

**Issue by Abbybretado** [AmericaSCORESBayArea/student-registration#241] opened 2024-04-25 19:42 UTC
**Describe the issue**
Web form does not allow for enrollment into team seasons. 

**Expected behavior**
Web form should look up current seasons and allow users to select teams to create a student record and enroll the student.

This is the general model @Abbybretado proposes which looks fine to me, for now. In the future we may look again at these three drop-downs as key moments to connect with Families.

![Image](https://github.com/AmericaSCORESBayArea/student-registration/assets/1458369/1045b899-7fa8-4bff-9a0d-cce227794192)

**Comment by CritiqalPete** [comment] 2024-04-25 20:06
not sure how the notification fits with the title being about enrollment. Separate ticket maybe?
Unless the notification explains how enrollment works?

**Comment by CritiqalPete** [comment] 2024-04-25 20:11
let's come up with a really nice UX. A Guide?
_How to choose the right team_ Will need help from Program on this.

**Comment by CritiqalPete** [comment] 2024-04-28 19:15
@Abbybretado work is starting on this immediately so let's stay tuned for updates and questions from @lautirozen

**Comment by CritiqalPete** [comment] 2024-04-29 23:41
closing as duplicate of https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/issues/74

**Closed** 2024-04-29 23:42 UTC
Labels: enhancement
